# Generated by Django 5.2.8 on 2026-07-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="hr_message",
            field=models.TextField(
                blank=True,
                help_text="Custom message from HR when accepting or rejecting",
                null=True,
            ),
        ),
    ]
