# Generated by Django 6.0.1 on 2026-01-16 16:04

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('job_seeker', 'Job Seeker'), ('hr', 'HR'), ('admin', 'Admin')], default='job_seeker', max_length=20)),
                ('profile_picture', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_pictures')),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('is_google_user', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HRProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_email', models.EmailField(max_length=254)),
                ('ntn_number', models.CharField(help_text='National Tax Number', max_length=50)),
                ('interview_date', models.DateField(help_text='Date when you last conducted an interview')),
                ('approval_letter', cloudinary.models.CloudinaryField(max_length=255, verbose_name='approval_letters')),
                ('designation', models.CharField(blank=True, choices=[('junior_hr_executive', 'Junior HR Executive'), ('senior_hr_executive', 'Senior HR Executive'), ('hr_manager', 'HR Manager'), ('talent_acquisition', 'Talent Acquisition Specialist'), ('recruitment_lead', 'Recruitment Lead'), ('hr_director', 'HR Director')], max_length=50, null=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_hrs', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HR Profile',
                'verbose_name_plural': 'HR Profiles',
                'db_table': 'hr_profiles',
            },
        ),
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('university', models.CharField(blank=True, max_length=255, null=True)),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('degree', models.CharField(blank=True, max_length=255, null=True)),
                ('field_of_study', models.CharField(blank=True, max_length=255, null=True)),
                ('tokens_balance', models.PositiveIntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_seeker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Seeker Profile',
                'verbose_name_plural': 'Job Seeker Profiles',
                'db_table': 'job_seeker_profiles',
            },
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_resets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('initial', 'Initial Balance'), ('purchase', 'Purchase'), ('resume', 'Resume Generation'), ('cover_letter', 'Cover Letter Generation'), ('cold_email', 'Cold Email Generation'), ('skillbot', 'SkillBot Query'), ('mock_interview', 'Mock Interview'), ('future_trends', 'Future Trends Query')], max_length=30)),
                ('amount', models.IntegerField()),
                ('balance_after', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_transactions', to='accounts.jobseekerprofile')),
            ],
            options={
                'db_table': 'token_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
