# Generated by Django 5.2.8 on 2026-02-14 15:05

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerEducation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_seeker_education',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='JobSeekerLanguage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('proficiency_percentage', models.PositiveIntegerField(default=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_seeker_languages',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='JobSeekerPortfolioItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='portfolio_images')),
                ('link', models.URLField(blank=True, null=True)),
                ('technologies', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_seeker_portfolio',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='JobSeekerSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.PositiveIntegerField(default=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_seeker_skills',
                'ordering': ['id'],
            },
        ),
    ]
