# Generated by Django 5.2.8 on 2026-02-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_jobseekereducation_jobseekerlanguage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='experience_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
