# Generated by Django 5.2.8 on 2026-07-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_jobseekerprofile_experience_level"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobseekereducation",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="jobseekereducation",
            name="end_date",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="jobseekereducation",
            name="field_of_study",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="jobseekereducation",
            name="is_current",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobseekereducation",
            name="start_date",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="jobseekereducation",
            name="year",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
