name: Deploy Django to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Remove unnecessary files
        run: |
          rm -rf careermate-frontend .venv .vscode logs webcroller
          rm -f *.env *.env.local check*.txt check*.py list_users.py user_details.py user_role.py run_migrations.py rozee-tmp.html test_cheerio2.js pysys.txt pyver.txt users_list.txt roadmap_debug.log

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'careermate-api'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .